### ISSUE TITLE
dbc2val: Exception after log file playback

### ISSUE THREAD

**Issue by int0x27** [eclipse/kuksa.val.feeders#152]
After provided candump log file is played back, the following exception is dumped:
```
2023-11-03 18:10:24,049 ERROR dbcfeederlib.canplayer: _process_log() failed
Traceback (most recent call last):
  File "/ext/git/boschglobal/kuksa.val.services-main/.vscode/scripts/assets/feedercan/0.4.1/dbc2val/dbcfeederlib/canplayer.py", line 86, in _tx_worker
    self._process_log()
  File "/ext/git/boschglobal/kuksa.val.services-main/.vscode/scripts/assets/feedercan/0.4.1/dbc2val/dbcfeederlib/canplayer.py", line 53, in _process_log
    for msg in log_reader:
  File "/home/ikk/.pyenv/versions/3.9.18/lib/python3.9/site-packages/can/io/player.py", line 147, in __iter__
    for message in self.raw_messages:
  File "/home/ikk/.pyenv/versions/3.9.18/lib/python3.9/site-packages/can/io/canutils.py", line 51, in __iter__
    for line in self.file:
ValueError: I/O operation on closed file.
2023-11-03 18:10:24,049 INFO dbcfeederlib.canplayer: Stopped writing CAN messages to bus
```
I tried to fix it and it appars that
`can.MessageSync(messages=self._messages, timestamps=True)` closes the file opened in `self._messages = can.LogReader(dumpfile)`

The question is do we loop the playback (I think there was such option in feedercan) or feeder should stop after file has been replayed?

Proposed fix for continuous playback:
```python
    def __init__(self, dumpfile: str, can_port: str):
        self._running = False
        self._dumpfile = dumpfile
        ...

    def _process_log(self):
        # using MessageSync in order to consider timestamps of CAN messages
        # and the delays between them
        messages = can.LogReader(self._dumpfile)
        log_reader = can.MessageSync(messages=messages, timestamps=True)
        for msg in log_reader:
            if not self._running or not self._bus:
                return
            try:
                self._bus.send(msg)
                if log.isEnabledFor(logging.DEBUG):
                    log.debug("Sent message [channel: %s]: %s", self._bus.channel_info, msg)
            except can.CanError:
                log.error("Failed to send message via CAN bus")

        log.info("Replayed all messages from CAN log file")

    def _tx_worker(self):
        log.info("Starting to write CAN messages to bus")
        try:
            while self._running:
                self._process_log()
        except:
            log.error("_process_log() failed", exc_info=True)
        log.info("Stopped writing CAN messages to bus")
```

**Comment by erikbosch** [comment]
@int0x27 -can you provide information how you start the feeder, i.e. the command line?
