### ISSUE TITLE
J1939 support in dbcfeeder

### ISSUE THREAD

**Issue by erikbosch** [eclipse/kuksa.val.feeders#56]
When trying to run dbcfeeder in j1939 mode the following error is observed. It seems to depend on:

- The[ J1939 module](https://pypi.org/project/j1939/) is old.  [Source code](https://github.com/benkfra/j1939) has not been updated since 2018.
- It calls `can.Message` with `extended_id`.
- That argument was renamed to `is_extended_id` starting with [python-can](https://python-can.readthedocs.io/en/v4.1.0/message.html) v3.0, latest version is v4.1
- So if we want to continue to use this j1939 package we need to restrict our python-can version in `requirements.txt`
- We might otherwise consider changing to alternative j1939 packages, like https://pypi.org/project/can-j1939/

```
Exception in thread j1939.ecu job_thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/erik/.local/lib/python3.10/site-packages/j1939/electronic_control_unit.py", line 171, in _async_job_thread
    if event['callback']( event['cookie'] ) == True:
  File "/home/erik/.local/lib/python3.10/site-packages/j1939/controller_application.py", line 85, in _process_claim_async
    self._send_address_claimed(self._device_address_announced)
  File "/home/erik/.local/lib/python3.10/site-packages/j1939/controller_application.py", line 204, in _send_address_claimed
    self._ecu.send_message(mid.can_id, data)
  File "/home/erik/.local/lib/python3.10/site-packages/j1939/electronic_control_unit.py", line 579, in send_message
    msg = can.Message(extended_id=True,
TypeError: Message.__init__() got an unexpected keyword argument 'extended_id'
```

**Comment by erikbosch** [comment]
Can be closed when #57 is merged
